[template]
cargo_generate_version = ">=0.10.0"
init = true
ignore = [
    "cargo-generate.toml",
    "target/**",
    "target/",
    ".cargo-ok",
    "Cargo.lock",
    "**/.DS_Store",
    "TEMPLATE_README.md",
    "test.sh",
]

[placeholders]
server_port = { type = "string", prompt = "What port should the server run on?", default = "3000" }

[placeholders.use_redpanda]
type = "bool"
prompt = "Do you want to use Redpanda?"
default = true

[conditional.'use_redpanda == false']
ignore = [
    "src/infrastructure",
    "src/events",
    "src/domains/order/event_handlers.rs",
    "src/domains/order/topic_handler.rs",
    "src/domains/logistics/event_handlers.rs",
    "src/domains/logistics/topic_handler.rs",
]

[binary]
extensions = [
    "bin",
    "woff",
    "woff2",
    "ttf",
    "otf",
    "eot",
    "jpg",
    "jpeg",
    "png",
    "gif",
    "svg",
    "ico",
    "mp4",
    "webm",
    "ogg",
    "mp3",
    "wav",
    "pdf",
    "zip",
    "tar",
    "gz",
    "lock",
]

paths = [
    "**/.fingerprint/**/*",
    "**/incremental/**/*",
    "**/deps/**/*",
    "target/**/*",
    "target",
    "**/.DS_Store",
]
